### PR TITLE
With this fixes sqlite should work with new nodes.

### PR DESCRIPTION
**Pull request by rbochenski**
Fixing sources to work with nodes 0.6.x
I have added extends module. Perhaps it should be done in different way.

### CODE REVIEW

**Comment by rbochenski** [comment]
This two commits should be merged to work properly.

**Comment by ndaversa** [comment]
@rbochenski

Error: Cannot find module './sqlite3_bindings'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/Users/ndaversa/sample/node_modules/sqlite/sqlite.js:19:14)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)

**Comment by rbochenski** [comment]
Just link build/Release/sqlite3_bindings.node into sqlite3_bindings sqlite dir.
I am not sure how to do it properly during compilation/installation.

**Comment by panzi** [comment]
I fixed the "Cannot find module './sqlite3_bindings'" error differently: https://github.com/panzi/node-sqlite/commit/f6791b9e9c2418fc43f9b9e76ace1e6a39c11d8a
No idea if this is better.
